name: Fazer deploy na VPS após commit

on:
  push:
    branches:
      - main  # altere para a branch que deseja monitorar

jobs:
  executar-url:
    runs-on: ubuntu-latest

    steps:
    - name: Curl para executar a URL
      run: curl -X POST http://89.116.73.154:3000/api/deploy/e9089ae3882b4e294040bc3ca41a42dc7c8869b83cc1232d
